[versions]
# App Versions
versionCode = "232"
versionName = "0.4.0-alpha02"
coroutines = "1.11.0-rc02"
coreKtx = "1.19.0-alpha01"
swipeRefresh = "1.2.0"
# 👇 Firebase Versions
googleServices = "4.4.4"
firebaseBom = "34.12.0"
xposedApi = "82"

# SDK Versions
compileSdk = "37"
buildTools = "37.0.0"
minSdk = "30"
targetSdk = "37"

# Plugins
agp = "9.3.0-alpha02"
kotlin = "2.4.0-Beta2"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefresh" }

# 👇 Firebase Libraries
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposedApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# 👇 Google Services Plugin
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
